/**
 * Build-time generator for the low-poly hex world's VISUAL grid.
 *
 * Exploration tracking runs at H3 res 10 (fine, per {@link H3_RESOLUTION}); the
 * on-screen hex tiles are drawn at a coarser VISUAL resolution so the map reads
 * as a chunky low-poly board of ~hundreds of tiles instead of ~40k slivers. This
 * script tiles Singapore's *land* at that visual resolution and writes the cell
 * id list into `src/data/landHexCells.ts`.
 *
 * We precompute the id list (not the geometry) because it's tiny (~1 line per
 * cell) and the app rebuilds the hex boundaries from ids at load — far smaller
 * than shipping the full boundary GeoJSON, and the land polygon never changes.
 *
 * Usage:
 *   1. scripts/singapore_land.geojson must exist (same source as buildLandCells).
 *   2. Run:  npm run build:land-hex
 *
 * ⚠️ VISUAL_RES below MUST equal VISUAL_H3_RESOLUTION in
 *    src/config/explorationConfig.ts. Change one → re-run this script.
 */
import fs from 'node:fs';
import path from 'node:path';

import { polygonToCells } from 'h3-js';

const VISUAL_RES = 8; // keep in sync with VISUAL_H3_RESOLUTION
const GEOJSON_PATH = path.join(__dirname, 'singapore_land.geojson');
const OUT_PATH = path.join(__dirname, '..', 'src', 'data', 'landHexCells.ts');

type Ring = number[][];
type PolyCoords = Ring[];

function toPolygons(geojson: any): PolyCoords[] {
  const out: PolyCoords[] = [];
  const collect = (g: any) => {
    if (!g) return;
    if (g.type === 'Polygon') out.push(g.coordinates);
    else if (g.type === 'MultiPolygon') g.coordinates.forEach((p: PolyCoords) => out.push(p));
    else if (g.type === 'Feature') collect(g.geometry);
    else if (g.type === 'FeatureCollection') g.features.forEach((f: any) => collect(f.geometry));
    else if (g.type === 'GeometryCollection') g.geometries.forEach(collect);
  };
  collect(geojson);
  return out;
}

function main() {
  if (!fs.existsSync(GEOJSON_PATH)) {
    console.error(`Missing ${GEOJSON_PATH}. Drop a Singapore land GeoJSON there first.`);
    process.exit(1);
  }

  const gj = JSON.parse(fs.readFileSync(GEOJSON_PATH, 'utf8'));
  const cells = new Set<string>();
  for (const poly of toPolygons(gj)) {
    // `true` = coordinates are GeoJSON [lng, lat] order.
    polygonToCells(poly, VISUAL_RES, true).forEach((c) => cells.add(c));
  }

  const ids = [...cells].sort();
  const banner = `// AUTO-GENERATED by scripts/buildLandHexCells.ts — H3 res ${VISUAL_RES}. Do not edit by hand.\n`;
  const body = `export const LAND_HEX_CELLS: readonly string[] = ${JSON.stringify(ids)};\n`;
  fs.writeFileSync(OUT_PATH, banner + body);
  console.log('LAND_HEX_CELLS =', ids.length, '→', path.relative(process.cwd(), OUT_PATH));
}

main();
