/**
 * Build-time denominator generator for the exploration progress badge.
 *
 * Computes how many H3 cells (at the app's resolution) tile Singapore's *land*,
 * once, and writes the count as a constant into `src/data/singaporeLandCells.ts`.
 * We do this at build time rather than at runtime because polygon-filling all of
 * Singapore is expensive and the answer never changes between runs.
 *
 * Usage:
 *   1. Place a Singapore land polygon (GeoJSON) at scripts/singapore_land.geojson
 *      — a Feature, Geometry, or FeatureCollection of Polygon/MultiPolygon.
 *      Sources: Natural Earth admin-0, or an OSM administrative boundary export.
 *   2. Run:  npm run build:land-cells
 *
 * ⚠️ RES below MUST equal H3_RESOLUTION in src/config/explorationConfig.ts.
 *    If you change the app resolution, re-run this script or the % will be off.
 */
import fs from 'node:fs';
import path from 'node:path';

import { polygonToCells } from 'h3-js';

const RES = 10; // keep in sync with H3_RESOLUTION
const GEOJSON_PATH = path.join(__dirname, 'singapore_land.geojson');
const OUT_PATH = path.join(__dirname, '..', 'src', 'data', 'singaporeLandCells.ts');

type Ring = number[][];
type PolyCoords = Ring[];

function toPolygons(geojson: any): PolyCoords[] {
  const geom = geojson.type === 'FeatureCollection'
    ? { type: 'GeometryCollection', geometries: geojson.features.map((f: any) => f.geometry) }
    : geojson.type === 'Feature'
      ? geojson.geometry
      : geojson;

  const out: PolyCoords[] = [];
  const collect = (g: any) => {
    if (!g) return;
    if (g.type === 'Polygon') out.push(g.coordinates);
    else if (g.type === 'MultiPolygon') g.coordinates.forEach((p: PolyCoords) => out.push(p));
    else if (g.type === 'GeometryCollection') g.geometries.forEach(collect);
  };
  collect(geom);
  return out;
}

function main() {
  if (!fs.existsSync(GEOJSON_PATH)) {
    console.error(`Missing ${GEOJSON_PATH}. Drop a Singapore land GeoJSON there first.`);
    process.exit(1);
  }

  const gj = JSON.parse(fs.readFileSync(GEOJSON_PATH, 'utf8'));
  const polys = toPolygons(gj);

  const cells = new Set<string>();
  for (const poly of polys) {
    // `true` = coordinates are GeoJSON [lng, lat] order.
    polygonToCells(poly, RES, true).forEach((c) => cells.add(c));
  }

  const banner = `// AUTO-GENERATED by scripts/buildLandCells.ts — H3 res ${RES}. Do not edit by hand.\n`;
  fs.writeFileSync(
    OUT_PATH,
    `${banner}export const TOTAL_LAND_CELLS = ${cells.size};\n`,
  );
  console.log('TOTAL_LAND_CELLS =', cells.size, '→', path.relative(process.cwd(), OUT_PATH));
}

main();
