import type { ImageEntry } from "@maplibre/maplibre-react-native";

/**
 * AUTO-GENERATED — do not edit by hand.
 * Regenerate after changing assets/landmark-icons/ (see scripts note below).
 *
 * Small (256×256 PNG) landmark marker icons for the map SymbolLayer, keyed by
 * landmark id. These are DOWNSCALED, PNG copies of the 1920×1920 hero webp in
 * assets/landmarks/ — the full-size webp overflowed MapLibre's icon atlas (it
 * rendered as torn horizontal streaks) and risked webp decode issues on native.
 * The detail sheet still uses the original webp via Landmark.image; only the
 * map marker uses these.
 *
 * Metro can't require() by a runtime-computed path, so every icon is enumerated
 * here as a static require and looked up by id in LandmarkSymbols.
 */
export const LANDMARK_ICONS: Record<string, ImageEntry> = {
  "adventure-cove-waterpark": require("../../../assets/landmark-icons/adventure-cove-waterpark.png"),
  "armenian-church": require("../../../assets/landmark-icons/armenian-church.png"),
  "artscience-museum": require("../../../assets/landmark-icons/artscience-museum.png"),
  "asian-civilisations-museum": require("../../../assets/landmark-icons/asian-civilisations-museum.png"),
  "bird-paradise": require("../../../assets/landmark-icons/bird-paradise.png"),
  "bishan-ang-mo-kio-park": require("../../../assets/landmark-icons/bishan-ang-mo-kio-park.png"),
  "boat-quay": require("../../../assets/landmark-icons/boat-quay.png"),
  "buddha-tooth-relic-temple": require("../../../assets/landmark-icons/buddha-tooth-relic-temple.png"),
  "bugis-street": require("../../../assets/landmark-icons/bugis-street.png"),
  "bukit-timah-nature-reserve": require("../../../assets/landmark-icons/bukit-timah-nature-reserve.png"),
  "cavenagh-bridge": require("../../../assets/landmark-icons/cavenagh-bridge.png"),
  "changi-beach-park": require("../../../assets/landmark-icons/changi-beach-park.png"),
  "changi-chapel-museum": require("../../../assets/landmark-icons/changi-chapel-museum.png"),
  "changi-jurassic-mile": require("../../../assets/landmark-icons/changi-jurassic-mile.png"),
  "chijmes": require("../../../assets/landmark-icons/chijmes.png"),
  "chinatown": require("../../../assets/landmark-icons/chinatown.png"),
  "chinatown-complex-food-centre": require("../../../assets/landmark-icons/chinatown-complex-food-centre.png"),
  "chinese-garden": require("../../../assets/landmark-icons/chinese-garden.png"),
  "clarke-quay": require("../../../assets/landmark-icons/clarke-quay.png"),
  "coney-island": require("../../../assets/landmark-icons/coney-island.png"),
  "dempsey-hill": require("../../../assets/landmark-icons/dempsey-hill.png"),
  "east-coast-park": require("../../../assets/landmark-icons/east-coast-park.png"),
  "esplanade": require("../../../assets/landmark-icons/esplanade.png"),
  "fort-canning-park": require("../../../assets/landmark-icons/fort-canning-park.png"),
  "fort-siloso": require("../../../assets/landmark-icons/fort-siloso.png"),
  "fountain-of-wealth": require("../../../assets/landmark-icons/fountain-of-wealth.png"),
  "gardens-by-the-bay": require("../../../assets/landmark-icons/gardens-by-the-bay.png"),
  "geylang-serai-market": require("../../../assets/landmark-icons/geylang-serai-market.png"),
  "gillman-barracks": require("../../../assets/landmark-icons/gillman-barracks.png"),
  "haji-lane": require("../../../assets/landmark-icons/haji-lane.png"),
  "haw-par-villa": require("../../../assets/landmark-icons/haw-par-villa.png"),
  "helix-bridge": require("../../../assets/landmark-icons/helix-bridge.png"),
  "henderson-waves": require("../../../assets/landmark-icons/henderson-waves.png"),
  "holland-village": require("../../../assets/landmark-icons/holland-village.png"),
  "ion-orchard": require("../../../assets/landmark-icons/ion-orchard.png"),
  "jewel-changi-airport": require("../../../assets/landmark-icons/jewel-changi-airport.png"),
  "jurong-lake-gardens": require("../../../assets/landmark-icons/jurong-lake-gardens.png"),
  "kong-meng-san": require("../../../assets/landmark-icons/kong-meng-san.png"),
  "labrador-nature-reserve": require("../../../assets/landmark-icons/labrador-nature-reserve.png"),
  "lau-pa-sat": require("../../../assets/landmark-icons/lau-pa-sat.png"),
  "little-india": require("../../../assets/landmark-icons/little-india.png"),
  "macritchie-reservoir": require("../../../assets/landmark-icons/macritchie-reservoir.png"),
  "malay-heritage-centre": require("../../../assets/landmark-icons/malay-heritage-centre.png"),
  "marina-barrage": require("../../../assets/landmark-icons/marina-barrage.png"),
  "marina-bay-sands": require("../../../assets/landmark-icons/marina-bay-sands.png"),
  "masjid-jamae": require("../../../assets/landmark-icons/masjid-jamae.png"),
  "maxwell-food-centre": require("../../../assets/landmark-icons/maxwell-food-centre.png"),
  "merlion-park": require("../../../assets/landmark-icons/merlion-park.png"),
  "mount-faber-park": require("../../../assets/landmark-icons/mount-faber-park.png"),
  "mustafa-centre": require("../../../assets/landmark-icons/mustafa-centre.png"),
  "national-gallery-singapore": require("../../../assets/landmark-icons/national-gallery-singapore.png"),
  "national-museum-singapore": require("../../../assets/landmark-icons/national-museum-singapore.png"),
  "national-stadium": require("../../../assets/landmark-icons/national-stadium.png"),
  "newton-food-centre": require("../../../assets/landmark-icons/newton-food-centre.png"),
  "night-safari": require("../../../assets/landmark-icons/night-safari.png"),
  "old-airport-road-food-centre": require("../../../assets/landmark-icons/old-airport-road-food-centre.png"),
  "orchard-road": require("../../../assets/landmark-icons/orchard-road.png"),
  "palawan-beach": require("../../../assets/landmark-icons/palawan-beach.png"),
  "parliament-house": require("../../../assets/landmark-icons/parliament-house.png"),
  "pasir-ris-park": require("../../../assets/landmark-icons/pasir-ris-park.png"),
  "peranakan-houses-joo-chiat": require("../../../assets/landmark-icons/peranakan-houses-joo-chiat.png"),
  "peranakan-museum": require("../../../assets/landmark-icons/peranakan-museum.png"),
  "pinnacle-duxton-skybridge": require("../../../assets/landmark-icons/pinnacle-duxton-skybridge.png"),
  "pulau-ubin": require("../../../assets/landmark-icons/pulau-ubin.png"),
  "raffles-hotel": require("../../../assets/landmark-icons/raffles-hotel.png"),
  "river-wonders": require("../../../assets/landmark-icons/river-wonders.png"),
  "robertson-quay": require("../../../assets/landmark-icons/robertson-quay.png"),
  "science-centre-singapore": require("../../../assets/landmark-icons/science-centre-singapore.png"),
  "sentosa-island": require("../../../assets/landmark-icons/sentosa-island.png"),
  "siloso-beach": require("../../../assets/landmark-icons/siloso-beach.png"),
  "singapore-art-museum": require("../../../assets/landmark-icons/singapore-art-museum.png"),
  "singapore-botanic-gardens": require("../../../assets/landmark-icons/singapore-botanic-gardens.png"),
  "singapore-cable-car": require("../../../assets/landmark-icons/singapore-cable-car.png"),
  "singapore-city-gallery": require("../../../assets/landmark-icons/singapore-city-gallery.png"),
  "singapore-flyer": require("../../../assets/landmark-icons/singapore-flyer.png"),
  "singapore-oceanarium": require("../../../assets/landmark-icons/singapore-oceanarium.png"),
  "singapore-zoo": require("../../../assets/landmark-icons/singapore-zoo.png"),
  "skyhelix-sentosa": require("../../../assets/landmark-icons/skyhelix-sentosa.png"),
  "skyline-luge-sentosa": require("../../../assets/landmark-icons/skyline-luge-sentosa.png"),
  "skypark-observation-deck": require("../../../assets/landmark-icons/skypark-observation-deck.png"),
  "sri-mariamman-temple": require("../../../assets/landmark-icons/sri-mariamman-temple.png"),
  "sri-srinivasa-perumal-temple": require("../../../assets/landmark-icons/sri-srinivasa-perumal-temple.png"),
  "sri-thendayuthapani-temple": require("../../../assets/landmark-icons/sri-thendayuthapani-temple.png"),
  "sri-veeramakaliamman-temple": require("../../../assets/landmark-icons/sri-veeramakaliamman-temple.png"),
  "st-andrews-cathedral": require("../../../assets/landmark-icons/st-andrews-cathedral.png"),
  "sultan-mosque": require("../../../assets/landmark-icons/sultan-mosque.png"),
  "sungei-buloh-wetland-reserve": require("../../../assets/landmark-icons/sungei-buloh-wetland-reserve.png"),
  "tanjong-beach": require("../../../assets/landmark-icons/tanjong-beach.png"),
  "tekka-centre": require("../../../assets/landmark-icons/tekka-centre.png"),
  "temple-of-1000-lights": require("../../../assets/landmark-icons/temple-of-1000-lights.png"),
  "the-intan": require("../../../assets/landmark-icons/the-intan.png"),
  "the-istana": require("../../../assets/landmark-icons/the-istana.png"),
  "the-shoppes-mbs": require("../../../assets/landmark-icons/the-shoppes-mbs.png"),
  "thian-hock-keng-temple": require("../../../assets/landmark-icons/thian-hock-keng-temple.png"),
  "tiong-bahru-estate": require("../../../assets/landmark-icons/tiong-bahru-estate.png"),
  "tiong-bahru-market": require("../../../assets/landmark-icons/tiong-bahru-market.png"),
  "universal-studios-singapore": require("../../../assets/landmark-icons/universal-studios-singapore.png"),
  "vivocity": require("../../../assets/landmark-icons/vivocity.png"),
  "wild-wild-wet": require("../../../assets/landmark-icons/wild-wild-wet.png"),
  "wings-of-time": require("../../../assets/landmark-icons/wings-of-time.png"),
};
